event = {}

event.new = function(self,id,callback) end

EVENT_DATA_ID_INPUTED_STRING = 200
EVENT_DATA_ID_DAMAGE_SOURCE = 201
EVENT_DATA_ID_DAMAGE_TARGET = 202
EVENT_DATA_ID_DAMAGE_TYPE = 203
EVENT_DATA_ID_ATTACK_TYPE = 204
EVENT_DATA_ID_EVENT_DAMAGE = 205
EVENT_DATA_ID_DAMAGE_FLAGS = 206
EVENT_DATA_ID_INPUTED_KEY = 207
EVENT_DATA_ID_INPUTED_KEY_MODE = 208
EVENT_DATA_ID_PNETDATA = 209
EVENT_DATA_ID_SIMPLE_FLOAT = 210


EVENT_ID_CHAT_COMMAND = 400
EVENT_ID_SCREEN_UPDATE = 401
EVENT_ID_KEY_INPUT = 402
EVENT_ID_SCRIPT_LOADED = 403
EVENT_ID_UNIT_DAMAGED = 404
EVENT_ID_GAME_ENDED = 405
EVENT_ID_ON_TICK = 406


TextPrint = function(...) end
Log = function(...) end


function IntToHex(int) end
function ReadInt(ptr) end